(define (domain d1)
  (:requirements :typing)
  (:types X y)

  (:predicates
    (atx ?x - X)
    (aty ?y - y)
    (has_to_check) (can_move)
    (alive)
  )
  (:action check
    :parameters ()
    :precondition (has_to_check)
    :effect (and
      (not (has_to_check)) (can_move)
      (when (and (atx x_0) (aty y_4)) (not (alive)))
      (when (and (atx x_1) (aty y_4)) (and (not (alive))))
      (when (and (atx x_2) (aty y_4)) (and (not (alive))))
      (when (and (atx x_3) (aty y_4)) (and (not (alive))))
      (when (and (atx x_4) (aty y_4)) (and (not (alive))))
      (when (and (atx x_0) (aty y_0)) (and (not (alive))))
      (when (and (atx x_4) (aty y_0)) (and (not (alive))))
    )
  )
  (:action move_up
   :parameters ()
   :precondition (can_move)
   :effect (and
     (not (can_move)) (has_to_check)
      (when (aty y_0) (and (not (aty y_0)) (aty y_1)))
      (when (aty y_1) (and (not (aty y_1)) (aty y_2)))
      (when (aty y_2) (and (not (aty y_2)) (aty y_3)))
      (when (aty y_3) (and (not (aty y_3)) (aty y_4)))
    )
  )
  (:action move_down
   :parameters ()
   :precondition (can_move)
   :effect (and
     (not (can_move)) (has_to_check)
      (when (aty y_1) (and (not (aty y_1)) (aty y_0)))
      (when (aty y_2) (and (not (aty y_2)) (aty y_1)))
      (when (aty y_3) (and (not (aty y_3)) (aty y_2)))
      (when (aty y_4) (and (not (aty y_4)) (aty y_3)))
    )
  )
  (:action move_left
   :parameters ()
   :precondition (can_move)
   :effect (and
     (not (can_move)) (has_to_check)
      (when (atx x_1) (and (not (atx x_1)) (atx x_0)))
      (when (atx x_2) (and (not (atx x_2)) (atx x_1)))
      (when (atx x_3) (and (not (atx x_3)) (atx x_2)))
      (when (atx x_4) (and (not (atx x_4)) (atx x_3)))
    )
  )
  (:action move_right
   :parameters ()
   :precondition (can_move )
   :effect (and
     (not (can_move)) (has_to_check)
      (when (atx x_0) (and (not (atx x_0)) (atx x_1)))
      (when (atx x_1) (and (not (atx x_1)) (atx x_2)))
      (when (atx x_2) (and (not (atx x_2)) (atx x_3)))
      (when (atx x_3) (and (not (atx x_3)) (atx x_4)))
      (when (aty y_0) (oneof (aty y_0) (and (not (aty y_0)) (aty y_1))))
      (when (aty y_1) (oneof (aty y_1) (and (not (aty y_1)) (aty y_2))))
      (when (aty y_2) (oneof (aty y_2) (and (not (aty y_2)) (aty y_3))))
      (when (aty y_3) (oneof (aty y_3) (and (not (aty y_3)) (aty y_4))))
    )
  )
)